name: autoupdate
on:
  push:
    branches:
      - branch-1
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - name: Auto Update
        uses: chinthakagodawita/autoupdate@v1.6.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_MSG: "Branch was auto-updated."
          MERGE_CONFLICT_ACTION: "fail"

      - run: echo $conflicted

      - run: echo 'Merge conflicts found!'
        if: ${{ steps.autoupdate.outputs.conflicted }}

      - run: echo 'No merge conflicts'
        if: ${{ !steps.autoupdate.outputs.conflicted }}
